export const EDUCATION_QUEUE_PENDING = "EDUCATION_QUEUE_PENDING";
export const EDUCATION_QUEUE_FULFILLED = "EDUCATION_QUEUE_FULFILLED";
export const EDUCATION_QUEUE_REJECTED = "EDUCATION_QUEUE_REJECTED";
